sudo: required
language: node_js
node_js:
  - "10"
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g ganache-cli
script:
  - ganache-cli
  - sleep 2 # to make sure docker container is ready before compiling
  - npm run test
